### ISSUE TITLE
许可证文件缺失，考虑是否选择一个 LICENSE

### ISSUE THREAD

**Issue by lazyparser** [ruyisdk/ruyici#10]
如题。需要讨论下

**Comment by xen0n** [comment]
这未来最终会变成 RuyiSDK 软件源的 source package repo（构建与分发配置分离的设计），所以它最终也会是代码，可以复用与 RuyiSDK 其他代码形态贡献相同的 license 选择（即 Apache-2.0）。

**Comment by lazyparser** [comment]
同意 Apache 2
